version: "3.9" # optional since v1.27.0
services:
  access_converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./in/db.accdb:/data/in/db.accdb
      - ./out:/data/out
